version: '3.8'

name: matrio-test

services:
  db:
    container_name: matrio-test-db
    image: postgres
    ports:
      - 3432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matrio
    networks:
      - matrio-test-network

networks:
  matrio-test-network: